cookie:
  name: logincookie
server:
  port: 8088

web:
  father: .a.com

#jwt
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh